name: Checks
on:
  push:
  pull_request:
jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: '3.2'
      - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop
  test:
    name: Test (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', 'head']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: bundle exec rspec
