name: Checks
on:
  push:
  pull_request:
jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: '3.2'
      - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop
  test:
    name: Test (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', 'head']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: bundle exec rspec
